version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auroville-app
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 